Server side
aditirai-12/software-product-sprint pull request #5
Opened 2022-06-12 20:37 UTC by aditirai-12

2022-06-12 20:38 UTC, aditirai-12 commented
change servlet code to say "Hello Aditi!" when user clicks 'here'

2022-06-14 17:41 UTC, jdtyner requested changes

2022-06-14 17:41 UTC, jdtyner commented on portfolio/src/main/webapp/index.html
> +</html>t
>  t

remove

2022-06-14 17:51 UTC, jdtyner approved these changes

2022-06-18 22:46 UTC, merged